{{- $app := .Values.hyfaaScheduler -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ird-mgb-hyfaa.fullname" . }}-hyfaa-scheduler-data
  labels:
    {{- include "ird-mgb-hyfaa.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "ird-mgb-hyfaa.fullname" . }}-hyfaa-scheduler
spec:
  accessModes:
  - ReadWriteOnce
  {{- if $app.storage.storage_class_name }}
  storageClassName: {{ $app.storage.storage_class_name }}
  {{- end }}
  {{- if $app.storage.external }}
  volumeName: {{ $app.storage.pv_name }}
  {{- else }}
  volumeName: {{ include "ird-mgb-hyfaa.fullname" . }}-{{ $app.storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ $app.storage.size }}
