{{- if .Values.createDirectories -}}
{{- $app := .Values.hyfaaScheduler -}}
{{- if not $app.storage.external -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ird-mgb-hyfaa.fullname" . }}-{{ $app.storage.pv_name }}
spec:
  capacity:
    storage: {{ $app.storage.size | default "100Gi" }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: {{ .Values.rootStoragePath }}/{{ $app.storage.pv_name | replace "-" "_" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: h2o
          operator: In
          values:
          - "true"
{{- end }}
{{- end }}