{{- if (not .Values.hyfaaScheduler.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-hyfaa-scheduler-secret
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
type: Opaque
data:
  EODAG__HYDROWEB_NEXT__AUTH__CREDENTIALS__APIKEY: {{ .Values.hyfaaScheduler.auth.apikey | b64enc | quote }}
{{- end }}
