
{{- $app := .Values.varnish -}}
{{ if $app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sagui-platform.fullname" . }}-varnish
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "sagui-platform.fullname" . }}-varnish
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "sagui-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "sagui-platform.fullname" . }}-varnish
  template:
    metadata:
      labels:
        {{- include "sagui-platform.selectorLabels" . | nindent 8 }}
        org.sagui-platform.service/name: {{ include "sagui-platform.fullname" . }}-varnish
        app.kubernetes.io/component: {{ include "sagui-platform.fullname" . }}-varnish
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with $.Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with $app.securityContext }}
      securityContext: 
        {{- toYaml . | nindent 12 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: conf
        configMap:
          name: {{ include "sagui-platform.fullname" . }}-varnish-config
      containers:
      - name: varnish
        image: {{ $app.image.repository }}:{{ $app.image.tag | default "latest" }}
        imagePullPolicy: {{ $app.image.pullPolicy }}
        # command: 
        #   - tail
        #   - -f
        #   - /dev/null
        ports:
          - containerPort: 80
        env:
          - name: VARNISH_SIZE
            value: "50MB"
        volumeMounts:
        - name: conf
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
          readOnly: true
        - name: tmp
          mountPath: /var/lib/varnish/varnishd:exec
        # livenessProbe:
        #   httpGet:
        #     path: /backend/srv/eng/catalog.search
        #     port: 8080
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # startupProbe:
        #   tcpSocket:
        #     port: 8080
        #   failureThreshold: 5
        #   periodSeconds: 50
---
{{- end }}