
{{- $app := .Values.varnish -}}
{{ if $app.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sagui-platform.fullname" . }}-varnish-config
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/varnish/*").AsConfig | indent 2 }}
{{- end }}
