
{{- $app := .Values.varnish -}}
{{ if $app.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sagui-platform.fullname" . }}-varnish-config
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
data:
{{ if $app.config }}
  default.vcl: |
{{ $app.config | indent 4 }}
{{- else }}
{{ (.Files.Glob "config/varnish/*").AsConfig | indent 2 }}
{{- end }}

{{- end }}
