apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sk-harvesters.fullname" . }}-logs
  labels:
    {{- include "sk-harvesters.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "sk-harvesters.fullname" . }}-sk-harvesters
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.logs.storage_class_name }}
  storageClassName: {{ .Values.storage.logs.storage_class_name }}
  {{- end }}
  {{- if .Values.storage.logs.pv_name }}
  volumeName: {{ .Values.storage.logs.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.logs.size | default "100Mi" }}
