{{- if .Values.statsoffice.enabled }}
# Statsoffice data harvester
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sk-harvesters.fullname" . }}-statsoffice
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.statsoffice.schedule | default "23 01 * * 2" | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name:  logs
            persistentVolumeClaim:
              claimName: {{ include "sk-harvesters.fullname" . }}-logs
          containers:
          - name:  harvester-statsoffice
            image: {{ .Values.statsoffice.image | default "registry.gitlab.com/po-kraj-sk/so-harvester/so-harvester:latest"}}
            imagePullPolicy: IfNotPresent
            env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                    name: {{ .Values.statsoffice.databaseConnectionString.existingSecret.name | default (printf "%s-sk-harvesters-common-config" (include "sk-harvesters.fullname" .)) }}
                    key: {{ .Values.statsoffice.databaseConnectionString.existingSecret.key }}
                    optional: false
            - name: DB_SCHEMA
              value: {{ .Values.statsoffice.dbschema | default "statsoffice" | quote }}
            - name: CUBES_LIST
              value: {{ .Values.statsoffice.cubeslist | quote }}
            - name: LOCATIONS_REGEX_FILTER
              value: {{ .Values.statsoffice.locationsregexfilter | quote }}
            - name: INDEX_COLUMNS
              value: {{ .Values.statsoffice.indexcolumns | default "rok,obd" | quote }}
            - name: CONTACT_EMAIL
              value: {{ .Values.statsoffice.contactEmail | default "" | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.statsoffice.loglevel | default "INFO" | quote }}
            - name: LOG_FILE
              value: {{ .Values.statsoffice.logfile | default "/app/logs/so_harvester.log" }}
            - name: BE_CAREFUL
              value: {{ .Values.statsoffice.becareful | default "True" | quote }}
            - name: RETRY_CONNECT
              value: {{ .Values.upsvar.retry_connect | default "3" | quote }}
            - name: RETRY_BACKOFF
              value: {{ .Values.upsvar.retry_backoff | default "0.25" | quote }}
            - name: PROM_PUSHGATEWAY_URI
              value: {{ .Values.promPushgatewayUrl | default "" }}
            volumeMounts:
            - name: logs
              mountPath: /app/logs
          restartPolicy: Never
{{- end }}
