
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sagui-platform.fullname" . }}-nginx-home
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/nginx/*").AsConfig | indent 2 }}