{{- if .Values.smtp.enabled }}
{{- if (not .Values.smtp.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sagui-platform.fullname" . }}-smtp-secret
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
type: Opaque
data:
  EMAIL_HOST: {{ .Values.smtp.auth.host | b64enc | quote }}
  EMAIL_PORT: {{ .Values.smtp.auth.port | b64enc | quote }}
  EMAIL_USE_TLS: {{ .Values.smtp.auth.useTls | b64enc | quote }}
  EMAIL_HOST_USER: {{ .Values.smtp.auth.user | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.auth.password | b64enc | quote }}
{{- end }}
{{- end }}
