apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "volumes.fullname" . }}-backups-root-storage
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: {{ .Values.rootStoragePath }}/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: georchestra
          operator: In
          values:
          - "true"

---
