apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "volumes.fullname" . }}-web-pvc
  labels:
    {{- include "volumes.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "volumes.fullname" . }}-web-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.pvc.storage_class_name }}
  storageClassName: {{ .Values.pvc.storage_class_name }}
  {{- end }}
  {{- if .Values.pvc.web.pv_name }}
  volumeName: {{ include "volumes.fullname" . }}-{{ .Values.pvc.web.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.web.size }}
