{{- $app := .Values.backend -}}
{{- if $app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-backend-svc
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5000
  selector:
    {{- include "mgb-hyfaa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "mgb-hyfaa.fullname" . }}-backend
{{- end 
}}