apiVersion: v1
kind: Service
metadata:
  name: {{ include "sagui-platform.fullname" . }}-database-svc
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
  selector:
    {{- include "sagui-platform.selectorLabels" . | nindent 4 }}
    app: database
