{{- if .Values.pgTileserv.enabled }}
{{- if (not .Values.pgTileserv.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sagui-platform.fullname" . }}-pg-tileserv-secret
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.pgTileserv.auth.databaseUrl | b64enc | quote }}
{{- end }}
{{- end }}
