# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Nb of replicas of the PHP deployment. Does not affect the DB
# Change this to 0 to switch into maintenance/restore mode
replicaCount: 1

nodeSelector: {}

fqdn: "ksk-dev.pigeosolutions.fr"

storage:
  # storage_class_name: local-storage
  wordpress_html_content:
    # pv_name: wordpress-html-content
    size: 256Mi
  wordpress_mysql_data:
    # pv_name: wordpress-mysql-data
    size: 256Mi

# Configure the mysql connection
database:
  name: worpress
  mysqlRootPassword: verysecretpassW0rd
  mysqlUser: wp
  mysqlWordpressPassword: lesssecretpassW0rd

  # existingSecret needs to provide the expected env vars as provided by the
  # wordpress-config-secret.yaml file:

  # existingSecret:
  #   name: wordpress-config

image: wordpress:php7.4-apache
extraConfig: |
      define('PATH_CURRENT_SITE', '/home/' );
resources: {}
  # limits:
  #   memory: "100Mi"
  #   cpu: 10m
  # requests:
  #   memory: "50Mi"
  #   cpu: 5m
# datase for wordpress. mysql or mariadb
database:
  image: mysql:5.7
  resources: {}
  # limits:
  #   memory: "200Mi"
  #   cpu: 0.2
  # requests:
  #   memory: "100Mi"
  #   cpu: 0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}


ingress:
  enabled: false
  path: "/home/"
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts: []
  #  - host: georchestra-127-0-1-1.traefik.me
  tls: []
  # You can import TLS secrets using
  # kubectl create secret tls testsecret --key key.pem --cert cert.pem
  # Then specify the TLS secret name below.
  #  - secretName: testsecret
  #    hosts:
  #      - georchestra-127-0-1-1.traefik.me
  # define a custom incressClassName, like "traefik" or "nginx"
  className: ""
