{{- if (not .Values.hyfaaScheduler.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sagui-platform.fullname" . }}-hyfaa-scheduler-secret
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
type: Opaque
data:
  EODAG__HYDROWEB_NEXT__AUTH__CREDENTIALS__APIKEY: {{ .Values.hyfaaScheduler.auth.apikey | b64enc | quote }}
{{- end }}
