
{{- $app := .Values.frontendAssim -}}
{{- if $app.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-frontend-assim
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "mgb-hyfaa.fullname" . }}-frontend-assim
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mgb-hyfaa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "mgb-hyfaa.fullname" . }}-frontend-assim
  template:
    metadata:
      labels:
        {{- include "mgb-hyfaa.selectorLabels" . | nindent 8 }}
        org.mgb-hyfaa.service/name: {{ include "mgb-hyfaa.fullname" . }}-frontend-assim
        app.kubernetes.io/component: {{ include "mgb-hyfaa.fullname" . }}-frontend-assim
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with $.Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: frontend-assim-config
        configMap:
          name: {{ include "mgb-hyfaa.fullname" . }}-frontend-assim-cm
      {{- with $app.securityContext }}
      securityContext: 
        {{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
      - name: frontend
        image: {{ $app.image.repository }}:{{ $app.image.tag | default "latest" }}
        imagePullPolicy: {{ $app.image.pullPolicy }}
        ports:
          - containerPort: 80
        volumeMounts:
        - name: frontend-assim-config
          mountPath: /usr/share/nginx/html/assets/settings.json
          subPath: settings.json
        # livenessProbe:
        #   httpGet:
        #     path: /backend/srv/eng/catalog.search
        #     port: 8080
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # startupProbe:
        #   tcpSocket:
        #     port: 8080
        #   failureThreshold: 5
        #   periodSeconds: 50
---
{{- end }}