
{{- $app := .Values.frontendAssim -}}
{{- if $app.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ird-mgb-hyfaa.fullname" . }}-frontend-assim-svc
  labels:
    {{- include "ird-mgb-hyfaa.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
  selector:
    {{- include "ird-mgb-hyfaa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "ird-mgb-hyfaa.fullname" . }}-frontend-assim

{{- end }}