
{{- if (ge .Values.port "30000") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sshd-chrooted.fullname" . }}-sshd-svc
  labels:
    {{- include "sshd-chrooted.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: {{ .Values.port }}
  selector:
    {{- include "sshd-chrooted.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "sshd-chrooted.fullname" . }}-sshd

{{ else }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "sshd-chrooted.fullname" . }}-sshd-svc
  labels:
    {{- include "sshd-chrooted.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: 22
  selector:
    {{- include "sshd-chrooted.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "sshd-chrooted.fullname" . }}-sshd

{{- end }}