{{- if  .Values.authorizedKeys }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sshd-chrooted.fullname" . }}-sshd-authorized-keys
  labels:
    {{- include "sshd-chrooted.labels" . | nindent 4 }}
data:
{{- range .Values.authorizedKeys }}
  {{ .name }}: {{ .keys | nindent 4 }}
{{- end }}

{{- end }}