
{{- $app := .Values.pgTileserv -}}
{{- if $app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-pg-tileserv-svc
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
spec:
  ports:
    - port: 7800
  selector:
    {{- include "mgb-hyfaa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "mgb-hyfaa.fullname" . }}-pg-tileserv
{{- end }}