
{{- $app := .Values.pgTileserv -}}
{{- if $app.enabled }}
{{- if (not $app.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-pg-tileserv-secret
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ $app.auth.databaseUrl | b64enc | quote }}
{{- end }}
{{- end }}
