{{- if (not .Values.datafeeder.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databases.fullname" . }}-datafeeder-database-secret
  labels:
    {{- include "databases.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ .Values.datafeeder.auth.postgres_db | b64enc | quote }}
  host: {{ printf "%s-datafeeder-database-svc" (include "databases.fullname" .) | b64enc | quote  }}
  password: {{ .Values.datafeeder.auth.postgres_password | b64enc | quote }}
  port: 5432
  user: {{ .Values.datafeeder.auth.postgres_user | b64enc | quote }}
{{- end }}
