apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "databases.fullname" . }}-georchestra-database
  labels:
    {{- include "databases.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "databases.fullname" . }}-georchestra-database
  replicas: 1
  selector:
    matchLabels:
      {{- include "databases.selectorLabels" . | nindent 6 }}
      app: georchestra-database
  template:
    metadata:
      labels:
        {{- include "databases.selectorLabels" . | nindent 8 }}
        app: georchestra-database
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: {{ include "databases.fullname" . }}-georchestra-database-data
      # - name: postgresql-data
      #   hostPath:
      #     path: {{ .Values.rootStoragePath }}/postgis_userdb_data
      #     type: Directory
      - name: pgtune
        configMap:
          name: {{ include "databases.fullname" . }}-georchestra-database-pgtune
      containers:
      - name: georchestra-database
        image: {{ .Values.georchestraDatabase.image.repository }}:{{ .Values.georchestraDatabase.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.georchestraDatabase.image.pullPolicy | default "Always"}}
        ports:
          - containerPort: 5432
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.georchestraDatabase.auth.existingSecret | default (printf "%s-georchestra-database-secret" (include "databases.fullname" .)) }}
                  key: dbname
                  optional: false
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.georchestraDatabase.auth.existingSecret | default (printf "%s-georchestra-database-secret" (include "databases.fullname" .)) }}
                  key: user
                  optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.georchestraDatabase.auth.existingSecret | default (printf "%s-georchestra-database-secret" (include "databases.fullname" .)) }}
                  key: password
                  optional: false
          - name: PGTUNE_FOLDER
            value: "/cm/pgtune"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        - name: pgtune
          mountPath: /cm/pgtune
          readOnly: true
        resources:
          {{- toYaml .Values.georchestraDatabase.resources | nindent 12 }}
        startupProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 30
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
