{{- if .Values.georchestraDatabase.pgtuneConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "databases.fullname" . }}-georchestra-database-pgtune
  labels:
    {{- include "databases.labels" . | nindent 4 }}
data:
  pgtune.sql: |
{{ .Values.georchestraDatabase.pgtuneConfigMap | indent 4 }}
{{- end }}
