apiVersion: v1
kind: Service
metadata:
  name: {{ include "databases.fullname" . }}-georchestra-database-svc
  labels:
    {{- include "databases.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
  selector:
    {{- include "databases.selectorLabels" . | nindent 4 }}
    app: georchestra-database
