{{- if (not .Values.database.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-config-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.database.name | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.mysqlRootPassword | b64enc | quote }}
  MYSQL_USER: {{ .Values.database.mysqlUser | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.database.mysqlWordpressPassword | b64enc | quote }}
{{- end }}
