
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql-db
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    app: wordpress-mysql-db

---


apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-http-svc
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 443
      targetPort: 443
      name: websecure
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    app: wordpress
