apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress-html-content
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "wordpress.fullname" . }}-wordpress
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.storage_class_name }}
  storageClassName: {{ .Values.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.storage.wordpress_html_content.pv_name }}
  volumeName: {{ .Values.storage.wordpress_html_content.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.wordpress_html_content.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress-mysql-data
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "wordpress.fullname" . }}-wordpress
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.storage_class_name }}
  storageClassName: {{ .Values.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.storage.wordpress_mysql_data.pv_name }}
  volumeName: {{ .Values.storage.wordpress_mysql_data.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.wordpress_mysql_data.size }}