apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mviewer.fullname" . }}-mviewerstudio-conf
  labels:
    {{- include "mviewer.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "mviewer.fullname" . }}-mviewerstudio
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.storage_class_name }}
  storageClassName: {{ .Values.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.storage.mviewerstudio_conf.pv_name }}
  volumeName: {{ .Values.storage.mviewerstudio_conf.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.mviewerstudio_conf.size }}
