{{- if (not .Values.backend.auth.existingSecret ) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sagui-platform.fullname" . }}-backend-secret
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.backend.auth.djangoSecretKey | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.backend.auth.djangoSuperuserPassword | b64enc | quote }}
{{- end }}
