
{{- $app := .Values.backend -}}
{{ if $app.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sagui-platform.fullname" . }}-django-static-files
  labels:
    {{- include "sagui-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "sagui-platform.fullname" . }}-backend
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.backend.storage.storage_class_name }}
  storageClassName: {{ .Values.backend.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.backend.storage.external }}
  volumeName: {{ .Values.backend.storage.pv_name }}
  {{- else }}
  volumeName: {{ include "sagui-platform.fullname" . }}-{{ .Values.backend.storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.storage.size }}
 {{- end }}
