{{- $app := .Values.backend -}}
{{- if and $app.enabled .Values.createDirectories (not .Values.backend.storage.external)}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sagui-platform.fullname" . }}-{{ .Values.backend.storage.pv_name }}
spec:
  capacity:
    storage: {{ .Values.backend.storage.size | default "1Gi" }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: {{ .Values.rootStoragePath }}/{{ .Values.backend.storage.pv_name | replace "-" "_" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: h2o
          operator: In
          values:
          - "true"
{{- end }}