apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sftp.fullname" . }}-ssh-crontabs
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "sftp.fullname" . }}-ssh
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.crontab.storage_class_name }}
  storageClassName: {{ .Values.storage.crontab.storage_class_name }}
  {{- end }}
  {{- if .Values.storage.crontab.pv_name }}
  volumeName: {{ .Values.storage.crontab.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.crontab.size | default "50Mi" }}
