apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-ssh-ldappam-root-authorizedkeys
data:
  ssh_ldappam_root_authorizedkeys: {{ .Values.rootAuthorizedKeys | default "" }}
