{{- if (not .Values.database.auth.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-database-secret
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.auth.dbname | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.auth.postgres_user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.auth.postgres_password | b64enc | quote }}
{{- end }}
