
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-database-data
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "mgb-hyfaa.fullname" . }}-database
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.database.storage.storage_class_name }}
  storageClassName: {{ .Values.database.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.database.storage.external }}
  volumeName: {{ .Values.database.storage.pv_name }}
  {{- else }}
  volumeName: {{ include "mgb-hyfaa.fullname" . }}-{{ .Values.database.storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
