apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgb-hyfaa.fullname" . }}-database-svc
  labels:
    {{- include "mgb-hyfaa.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
  selector:
    {{- include "mgb-hyfaa.selectorLabels" . | nindent 4 }}
    app: database
